export const CREATE_UPDATE_REQUEST = 'EVENT_UPSERT_REQUEST';
export const CREATE_UPDATE_SUCCESS = 'EVENT_UPSERT_SUCCESS';
export const CREATE_UPDATE_FAILURE = 'EVENT_UPSERT_FAILURE';

export const ALL_EVENTS_REQUEST = 'ALL_EVENTS_REQUEST';
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS';
export const ALL_EVENTS_FAILURE = 'ALL_EVENTS_FAILURE';
